### ISSUE TITLE
Issue 1 - Use sizeof without allocating variabiles

### ISSUE THREAD

**Issue by umbertoloria** [SerenaFraD/Programmazione1#1]
The problem comes from the following codepath.
> EserciziProgrammazione1/SizeOf/sizeof.c

	int i;
	short int si;
	long int li;
	float f;
	double d;
	long double ld;
	
	printf("******** Dimensione ********\n");
	printf("Intero       %lu\n", sizeof(i));
	printf("Short int    %lu\n", sizeof(si));
	printf("Long int     %lu\n", sizeof(li));
	printf("Float        %lu\n", sizeof(f));
	printf("Double       %lu\n", sizeof(d));
	printf("Long double  %lu\n", sizeof(ld));

You can get **type sizes** just passing to **sizeof** the type name (so you don't phisically allocate those variables).

	printf("Intero       %lu\n", sizeof(int));
	printf("Short int    %lu\n", sizeof(short int));
	printf("Long int     %lu\n", sizeof(long int));
	printf("Float        %lu\n", sizeof(float));
	printf("Double       %lu\n", sizeof(double));
	printf("Long double  %lu\n", sizeof(long double));

**Comment by SerenaFraD** [comment]
Mi sembra una buona alternativa, in quanto mi permette di stampare la dimensione di tale tipo senza allocare memoria.
Grazie per il contributo
